ESUG/esug.github.io

- .travis.yml
- Rapport.txt
- pillar.conf
> bug fix: change baseurl value

- 2018-Conference/conf2018.pillar
- theme/default.template
- theme/style.css
- Footer is now fixed to end of the page
- Fix typo on image name .jpg instead of .jpeg
- Remove the line below the navbar
> Fix bottom footer

- 2018-Conference/talks/2018-Polito-ContributingToPharo.pillar
- 2018-Conference/talks/2018-Polito-Git.pillar
- 2018-Conference/talks/2018-Polito-Iceberg.pillar
Add Guille's bios
New talk on how to contribute to pharo
> Add bios + new talk

- 2018-Conference/conf2018.pillar
Add list of hotels in Cagliari
Fix a few typos
> Add list of hotels

- 2018-Conference/talks/2018-Winkler-Abap.pillar
I will also talk about my experiences with the software exploration tool Moose2Model. I change therefore title and abstrakt. I also added Test to the title.
> Add Moose2Model to title and abstract

- 2018-Conference/awardsSubmissions2018.pillar
Fixed medals width  in Awards submissions+result page
> Fixed medals width

- 2019-Conference/talks/2019-Talk-LiveTyping.pillar
Talk proposal about LiveTyping
> LiveTyping talk proposal

- 2019-Conference/talks/2019-GCotelli-Stargate.pillar
> Add talk proposal

- 2019-Conference/talks/2019-DancingLinks-Nocentini.pillar
A talk proposal about the technique of [*Dancing Links*](https://arxiv.org/abs/cs/0011047) introduced by Donald Knuth.
> Nocentini's talk proposal.

- 2019-Conference/talks/2019-Scarlet-SmallTalk.pillar
John McIntosh will present this talk, but will not be available on Monday
> Scarlet Smalltalk

- 2019-Conference/talks/2019-DesignMatters.pillar
- 2019-Conference/talks/2019-NaturalVersusArtificialSystems.pillar
- 2019-Conference/talks/2019-WebAppsUsingFomanticUI-ObjectGuild.pillar
Hi @Ducasse, as per your request, instead of email here is a PR with our proposed talks.
> Added Object Guild proposals for ESUG 2019 talks.

- 2019-Conference/talks/2019-Dawson-SmalltalkWeb.pillar
Presentation proposal for 2019 ESUG meeting.
> Ewan Dawson

- 2019-Conference/talks/2019-ObjectiveSmalltalk-Weiher.pillar
I'd like to present ObjectiveSmalltalk, http://objective.st
> ObjectiveSmalltalk

- 2019-Conference/talks/2019-vanOs-vanZuilen-SmalltalkApplicationPlayground.pillar
> Added StAPtalk.

- 2020-Conference/call2020.pillar
- 2020-Conference/conf2020.pillar
> Some extra info

- 2020-Conference/cfpIWST2020.pillar
Here is the updated important date for IWST20. The PC is currently built and will be update shortly in future PR.
> Update important dates for IWST20

- 2020-Conference/cfpIWST2020.pillar
> Update IWST submission dealine

- 2020-Conference/cfpIWST2020.pillar
Add more time for ISWT submissions
> Update IWST deadline

- 2020-Conference/cfpIWST2020.pillar
I updated the IWST page with the inscription for the virtual event and the dates! (Finally...)
> Update IWST page with IWST remote even date and registration

- 2020-Conference/cfpIWST2020.pillar
Only some details that were missing and typos
> Fix typos for the virtual event

- 2020-Conference/cfpIWST2020.pillar
Laurine Dargaud is missing from the authors
> Update authors list for Microdown

- .github/workflows/makefile.yml
You will probably get a failure for the deploy step but I do not have access to credentials of this project to see how to fix it.
> Move to github actions

- 2022-Conference/cfpIWST2022.pillar
Due to some requests, more time for submissions
> Change dates for IWST deadlines

- 2022-Conference/talks/Pharo10.pillar
- 2022-Conference/talks/applicationDevelopmentWithPharo.pillar
- 2022-Conference/talks/improvingSnapshotInPharo.pillar
- Pharo 10 Status
- Improving Snapshots in Pharo
- Application Development with Pharo
> Adding talks for ESUG

- 2022-Conference/talks/Glamorous-Toolkit.pillar
> Talk submission for ESUG 2022, Andrei Chis & Veit Heller—Glamorous Toolkit in 2022

- 2022-Conference/talks/Foster-VSCode.pillar
Please schedule this talk for Tuesday, Wednesday, or Thursday as I have travel conflicts on Monday and Friday. Thanks!
> Visual Studio Code as a Smalltalk IDE
